### PR TITLE
Fix color output on Windows

### LINKED ISSUE #128: Colour of gin's log
How can I remove ?[97;42m] and change it to color?
I have already used gin.DefaultWriter = colorable.NewColorableStdout()
Goland can show color on gin's log, but no color when the system is launched by air.

launched by air
image

launched by goland
image

launched by .exe
image

### PR DESCRIPTION
**Pull request by 8LWXpg**
Fix #128 

I simply compare `util_windows.go` with `util_unix.go`, and setting `c.Stdout`, `c.Stderr` seems to have resolve this issue.

## Screenshot

image

### CODE REVIEW

**Comment by 8LWXpg** [comment]
A question for this code:
Returning `stdout` and `stderr` then `io.Copy` seems redundant, since setting `c.Stdout = os.Stdout` and `c.Stderr = os.Stderr` basically does the same thing. Is there reason for this?

**Comment by cosmtrek** [comment]
@8LWXpg yes, the related code need to refactor 😄

File: runner/util_windows.go [hunk 1]
```diff
@@ -29,6 +30,10 @@ func (e *Engine) startCmd(cmd string) (*exec.Cmd, io.ReadCloser, io.ReadCloser,
 	if err != nil {
 		return nil, nil, nil, err
 	}
+
+	c.Stdout = os.Stdout
+	c.Stderr = os.Stderr
```
Comment (makiuchi-d) [inline runner/util_windows.go:35]: These are overwrite StdoutPipe and StderrPipe.
https://cs.opensource.google/go/go/+/refs/tags/go1.23.1:src/os/exec/exec.go;l=1067

These pipe calls above should be removed.
